/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import entidade.Cliente;
import entidade.Data;
import entidade.ItemVenda;
import entidade.Produto;
import entidade.Venda;
import facade.VendaFacade;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author belarmino
 */
public class OrcamentoVisao extends javax.swing.JDialog {

    /**
     * Creates new form VendaVisao
     */
    private Data data;
    private Produto produtoItem;
    private Cliente clienteVenda;
    private Venda venda;
    private VendaFacade facade;
    private ItemVenda item;
    double sub = 0;
    double acres = 0;
    double desc = 0;
    double total = 0;

    public OrcamentoVisao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        enableComponents(false);
        facade = new VendaFacade();
        data = new Data();
        jlbData.setText("" + data.pegaDataAtual());
    }

    private void enableComponents(boolean status) {
        for (Component comp : jpProduto.getComponents()) {
            comp.setEnabled(status);
        }

        for (Component comp : jpCarrinho.getComponents()) {
            comp.setEnabled(status);
        }
        for (Component comp : jpCliente.getComponents()) {
            comp.setEnabled(status);
        }
        for (Component comp : jpPagamento.getComponents()) {
            comp.setEnabled(status);
        }
        jbtAbrir.setEnabled(!status);
        jtfProduto.setEnabled(!jbtAbrir.isEnabled());
        jtfCliente.setEnabled(!jbtAbrir.isEnabled());
        jtItemVenda.setEnabled(!jbtAbrir.isEnabled());
        jbtCancelar.setEnabled(status);
        jbtGerar.setEnabled(!jbtAbrir.isEnabled());

    }

    private void clearProduct() {
        jtfProduto.setText(null);
        jtfQuantidade.setText(null);
    }

    private void updateTable() {
        itemVendaList.clear();
        itemVendaList.addAll(facade.searchItemByStatus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        vendaEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("db_tcc_miqueiasPU").createEntityManager();
        produtoQuery = java.beans.Beans.isDesignTime() ? null : vendaEntityManager.createQuery("SELECT p FROM Produto p");
        produtoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(produtoQuery.getResultList());
        itemVendaQuery = java.beans.Beans.isDesignTime() ? null : vendaEntityManager.createQuery("SELECT i FROM ItemVenda i WHERE i.status != 'closed'");
        itemVendaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(itemVendaQuery.getResultList());
        jpProduto = new javax.swing.JPanel();
        jlbProduto = new javax.swing.JLabel();
        jbtBuscarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JTextField();
        jtfProduto = new javax.swing.JTextField();
        jbtAdicionar = new javax.swing.JButton();
        jpCarrinho = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtItemVenda = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtAbrir = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtFechar = new javax.swing.JButton();
        jbtGerar = new javax.swing.JButton();
        jpPagamento = new javax.swing.JPanel();
        jlbSubtotal = new javax.swing.JLabel();
        jlbDesconto = new javax.swing.JLabel();
        jftSubtotal = new javax.swing.JFormattedTextField();
        jftDesconto = new javax.swing.JFormattedTextField();
        jlbAcrescimo = new javax.swing.JLabel();
        jftAcrescimo = new javax.swing.JFormattedTextField();
        jlbTotal = new javax.swing.JLabel();
        jftTotal = new javax.swing.JFormattedTextField();
        jlbFormaPagto = new javax.swing.JLabel();
        jcFormaPagto = new javax.swing.JComboBox();
        jlbParcelas = new javax.swing.JLabel();
        jtfParcelas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlbCidade = new javax.swing.JLabel();
        jlbData = new javax.swing.JLabel();
        jpCliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtBuscarCliente = new javax.swing.JButton();
        jtfCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jpProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbProduto.setText("Produto:");

        jbtBuscarProduto.setText("Buscar");
        jbtBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtItemVenda, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.quantidade}"), jtfQuantidade, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jbtAdicionar.setText("Adicionar");
        jbtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpProdutoLayout = new javax.swing.GroupLayout(jpProduto);
        jpProduto.setLayout(jpProdutoLayout);
        jpProdutoLayout.setHorizontalGroup(
            jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlbProduto))
                .addGap(18, 18, 18)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAdicionar)
                        .addGap(0, 375, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpProdutoLayout.setVerticalGroup(
            jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbProduto)
                    .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtAdicionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCarrinho.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtItemVenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtItemVenda.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, itemVendaList, jtItemVenda);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cod_itemVenda}"));
        columnBinding.setColumnName("Cod_item Venda");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${produto}"));
        columnBinding.setColumnName("Produto");
        columnBinding.setColumnClass(entidade.Produto.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidade}"));
        columnBinding.setColumnName("Quantidade");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${subtotal}"));
        columnBinding.setColumnName("Subtotal");
        columnBinding.setColumnClass(Double.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jtItemVenda);
        if (jtItemVenda.getColumnModel().getColumnCount() > 0) {
            jtItemVenda.getColumnModel().getColumn(0).setResizable(false);
            jtItemVenda.getColumnModel().getColumn(1).setResizable(false);
            jtItemVenda.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jpCarrinhoLayout = new javax.swing.GroupLayout(jpCarrinho);
        jpCarrinho.setLayout(jpCarrinhoLayout);
        jpCarrinhoLayout.setHorizontalGroup(
            jpCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jpCarrinhoLayout.setVerticalGroup(
            jpCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Add.png"))); // NOI18N
        jbtAbrir.setText("Abrir");
        jbtAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAbrirActionPerformed(evt);
            }
        });

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Cancel.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Home.png"))); // NOI18N
        jbtFechar.setText("Fechar");

        jbtGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Save.png"))); // NOI18N
        jbtGerar.setText("Gerar");
        jbtGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtGerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtFechar)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAbrir)
                    .addComponent(jbtFechar)
                    .addComponent(jbtGerar)
                    .addComponent(jbtCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbSubtotal.setText("SubTotal:");

        jlbDesconto.setText("Desconto:");

        jftSubtotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jlbAcrescimo.setText("Acrescimo:");

        jftAcrescimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftAcrescimoActionPerformed(evt);
            }
        });

        jlbTotal.setText("Total:");

        jlbFormaPagto.setText("Forma de pagto:");

        jcFormaPagto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlbParcelas.setText("Parcelas:");

        javax.swing.GroupLayout jpPagamentoLayout = new javax.swing.GroupLayout(jpPagamento);
        jpPagamento.setLayout(jpPagamentoLayout);
        jpPagamentoLayout.setHorizontalGroup(
            jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSubtotal)
                    .addComponent(jlbTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jftSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jftTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPagamentoLayout.createSequentialGroup()
                        .addComponent(jlbDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbAcrescimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPagamentoLayout.createSequentialGroup()
                        .addComponent(jlbFormaPagto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbParcelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPagamentoLayout.setVerticalGroup(
            jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSubtotal)
                    .addComponent(jlbDesconto)
                    .addComponent(jftSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAcrescimo)
                    .addComponent(jftAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTotal)
                    .addComponent(jftTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbFormaPagto)
                    .addComponent(jcFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbParcelas)
                    .addComponent(jtfParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbCidade.setText("Presidente Epitácio, ");

        jlbData.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbData)
                .addGap(165, 165, 165))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCidade)
                    .addComponent(jlbData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Cliente");

        jbtBuscarCliente.setText("Buscar");
        jbtBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarClienteActionPerformed(evt);
            }
        });

        jtfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpClienteLayout = new javax.swing.GroupLayout(jpCliente);
        jpCliente.setLayout(jpClienteLayout);
        jpClienteLayout.setHorizontalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpClienteLayout.setVerticalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbtBuscarCliente)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCarrinho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarProdutoActionPerformed
        String name = jtfProduto.getText();
        ProdutoBuscaVisao pbv = new ProdutoBuscaVisao(null, true, name);
        pbv.setVisible(true);
    }//GEN-LAST:event_jbtBuscarProdutoActionPerformed

    private void jbtBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarClienteActionPerformed
        String name = jtfCliente.getText();
        ClienteBuscaVisao cbv = new ClienteBuscaVisao(null, true, name);
        cbv.setVisible(true);
    }//GEN-LAST:event_jbtBuscarClienteActionPerformed

    private void jtfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClienteActionPerformed

    private void jftAcrescimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftAcrescimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftAcrescimoActionPerformed

    private void jbtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAdicionarActionPerformed
        if (jtfProduto.getText().isEmpty() || jtfQuantidade.getText().isEmpty()) {
            if (jtfProduto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Informe o produto!", null, JOptionPane.INFORMATION_MESSAGE);
            } else if (jtfQuantidade.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Informe a quantidade do produto!", null, JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            venda.setClient(clienteVenda);
            venda.setData(new Date());
            venda.setListaItem(null);

            int qtd = Integer.parseInt(jtfQuantidade.getText());
            item = new ItemVenda();
            item.setProduto(produtoItem);
            item.setQuantidade(qtd);
            item.setSale(venda);
            item.setStatus("opened");
            item.setSubtotal(produtoItem.getPrecoUnitario() * qtd);
            itemVendaList.add(item);

            for (ItemVenda i : itemVendaList) {
                sub += i.getSubtotal();
            }
            jftSubtotal.setText("" + sub);
            calculaTotal();
            clearProduct();
            updateTable();
        }
    }//GEN-LAST:event_jbtAdicionarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            setClient();
            setProduct();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jbtAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAbrirActionPerformed
        venda = new Venda();
        enableComponents(true);
    }//GEN-LAST:event_jbtAbrirActionPerformed

    private void jbtGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGerarActionPerformed
        //venda
        //items
    }//GEN-LAST:event_jbtGerarActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        enableComponents(false);
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void setClient() {
        clienteVenda = ClienteBuscaVisao.cliente;
        jtfCliente.setText(ClienteBuscaVisao.cliente.getNome());
    }

    private void setProduct() {
        produtoItem = ProdutoBuscaVisao.produto;
        jtfProduto.setText(ProdutoBuscaVisao.produto.getDescricao());
    }

    private void calculaTotal() {
        desc = Double.parseDouble(jftDesconto.getText());
        acres = Double.parseDouble(jftAcrescimo.getText());
        total = (sub - desc) + acres;
        jftTotal.setText("" + total);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrcamentoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrcamentoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrcamentoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrcamentoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OrcamentoVisao dialog = new OrcamentoVisao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<entidade.ItemVenda> itemVendaList;
    private javax.persistence.Query itemVendaQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtAbrir;
    private javax.swing.JButton jbtAdicionar;
    private javax.swing.JButton jbtBuscarCliente;
    private javax.swing.JButton jbtBuscarProduto;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JButton jbtGerar;
    private javax.swing.JComboBox jcFormaPagto;
    private javax.swing.JFormattedTextField jftAcrescimo;
    private javax.swing.JFormattedTextField jftDesconto;
    private javax.swing.JFormattedTextField jftSubtotal;
    private javax.swing.JFormattedTextField jftTotal;
    private javax.swing.JLabel jlbAcrescimo;
    private javax.swing.JLabel jlbCidade;
    private javax.swing.JLabel jlbData;
    private javax.swing.JLabel jlbDesconto;
    private javax.swing.JLabel jlbFormaPagto;
    private javax.swing.JLabel jlbParcelas;
    private javax.swing.JLabel jlbProduto;
    private javax.swing.JLabel jlbSubtotal;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JPanel jpCarrinho;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpPagamento;
    private javax.swing.JPanel jpProduto;
    private javax.swing.JTable jtItemVenda;
    private javax.swing.JTextField jtfCliente;
    private javax.swing.JTextField jtfParcelas;
    private javax.swing.JTextField jtfProduto;
    private javax.swing.JTextField jtfQuantidade;
    private java.util.List<entidade.Produto> produtoList;
    private javax.persistence.Query produtoQuery;
    private javax.persistence.EntityManager vendaEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
