/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import entidade.Produto;
import entidade.Usuario;
import facade.ProdutoFacade;
import java.util.List;
import javax.swing.JOptionPane;
import relatorio.ProdutosReport;

/**
 *
 * @author aluno
 */
public class Principal extends javax.swing.JFrame {

    private final Usuario user;

    public Principal(Usuario u, String par) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        if (par.equals("default")) {
            jmiGrupoProdutos.setVisible(false);
            jmiFornecedores.setVisible(false);
            jmiDespesas.setVisible(false);
        }
        user = u;
        jlbUser.setText(user.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpUser = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jlbUser = new javax.swing.JLabel();
        jbtDeslogar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmMovimentacao = new javax.swing.JMenu();
        jmiCompras = new javax.swing.JMenuItem();
        jmiVendas = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiGrupoProdutos = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenuItem();
        jmiFornecedores = new javax.swing.JMenuItem();
        jmiDespesas = new javax.swing.JMenuItem();
        jmRelatorios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGLMC - Interface v1");

        jpUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Usuário:");

        jlbUser.setText("user");

        jbtDeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Exit.png"))); // NOI18N
        jbtDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeslogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpUserLayout = new javax.swing.GroupLayout(jpUser);
        jpUser.setLayout(jpUserLayout);
        jpUserLayout.setHorizontalGroup(
            jpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 613, Short.MAX_VALUE)
                .addComponent(jbtDeslogar)
                .addGap(41, 41, 41))
        );
        jpUserLayout.setVerticalGroup(
            jpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserLayout.createSequentialGroup()
                .addGroup(jpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtDeslogar))
                    .addGroup(jpUserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jlbUser))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Cliente");
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Venda");
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtUsuario.setText("Usuário");
        jbtUsuario.setFocusPainted(false);
        jbtUsuario.setFocusable(false);
        jbtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(jpUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jmMovimentacao.setText("Movimentação");

        jmiCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jmiCompras.setText("Compras");
        jmiCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiComprasActionPerformed(evt);
            }
        });
        jmMovimentacao.add(jmiCompras);

        jmiVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jmiVendas.setText("Vendas");
        jmiVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendasActionPerformed(evt);
            }
        });
        jmMovimentacao.add(jmiVendas);

        jMenuItem4.setText("Pagamentos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmMovimentacao.add(jMenuItem4);

        jMenuBar1.add(jmMovimentacao);

        jmManutencao.setText("Manutenção");

        jmiClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiClientes);

        jmiGrupoProdutos.setText("Grupo de Produtos");
        jmiGrupoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGrupoProdutosActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiGrupoProdutos);

        jmiProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jmiProdutos.setText("Produtos");
        jmiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutosActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiProdutos);

        jmiFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jmiFornecedores.setText("Fornecedores");
        jmiFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedoresActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiFornecedores);

        jmiDespesas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jmiDespesas.setText("Despesas");
        jmiDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDespesasActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiDespesas);

        jMenuBar1.add(jmManutencao);

        jmRelatorios.setText("Relatórios");

        jMenuItem1.setText("Venda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmRelatorios.add(jMenuItem1);

        jMenuItem2.setText("Produtos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmRelatorios.add(jMenuItem2);

        jMenuBar1.add(jmRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiComprasActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        ClienteVisao cn = new ClienteVisao(this, true);
        cn.setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedoresActionPerformed
        FornecedorVisao fv = new FornecedorVisao(this, true, user);
        fv.setVisible(true);
    }//GEN-LAST:event_jmiFornecedoresActionPerformed

    private void jmiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutosActionPerformed
        ProdutosVisao pv = new ProdutosVisao(this, true);
        pv.setVisible(true);
    }//GEN-LAST:event_jmiProdutosActionPerformed

    private void jmiDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDespesasActionPerformed
        DespesaGerenciador dg = new DespesaGerenciador(this, true);
        dg.setVisible(true);
    }//GEN-LAST:event_jmiDespesasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        VendasReportManager vrm = new VendasReportManager();
        vrm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ProdutoFacade facade = new ProdutoFacade();
        List<Produto> produtoList = facade.searchAll();
        ProdutosReport pr = new ProdutosReport(produtoList);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendasActionPerformed
        VendaVisao vv = new VendaVisao(this, true);
        vv.setVisible(true);
    }//GEN-LAST:event_jmiVendasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        PagamentoVisao pv = new PagamentoVisao(this, true);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jmiGrupoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGrupoProdutosActionPerformed
        GrupoProdutoVisao gpv = new GrupoProdutoVisao(this, true);
        gpv.setVisible(true);
    }//GEN-LAST:event_jmiGrupoProdutosActionPerformed

    private void jbtDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeslogarActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Deseja realmente deslogar?");
        if (op == 0) {
            this.dispose();
            Login lv = new Login();
            lv.setVisible(true);
        }
    }//GEN-LAST:event_jbtDeslogarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ClienteVisao cn = new ClienteVisao(this, true);
        cn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VendaVisao vv = new VendaVisao(this, true);
        vv.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUsuarioActionPerformed
        UsuarioVisao uv = new UsuarioVisao(this, true);
        uv.setVisible(true);
    }//GEN-LAST:event_jbtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtDeslogar;
    private javax.swing.JButton jbtUsuario;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmMovimentacao;
    private javax.swing.JMenu jmRelatorios;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiCompras;
    private javax.swing.JMenuItem jmiDespesas;
    private javax.swing.JMenuItem jmiFornecedores;
    private javax.swing.JMenuItem jmiGrupoProdutos;
    private javax.swing.JMenuItem jmiProdutos;
    private javax.swing.JMenuItem jmiVendas;
    private javax.swing.JPanel jpUser;
    // End of variables declaration//GEN-END:variables
}
