/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.Barcode;
import com.lowagie.text.pdf.PdfContentByte;
import facade.VendaFacade;
import java.awt.Color;
import java.awt.Image;
import java.io.InputStream;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author aluno
 */
public class RelatorioForm extends javax.swing.JDialog {

    private VendaFacade facade;

    /**
     * Creates new form NewJDialog
     */
    public RelatorioForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        facade = new VendaFacade();
        System.out.println(new java.util.Date());
    }

    private JasperPrint generateReport() {
        try {

            //O CAMINHO (PATH) DA IMAGEM (LOGO) DO RELATORIO EH ENVIADO POR PARAMETRO.
            //ESSA PARTE SOMENTE EH NECESSARIA SE VC QUISER COLOCAR UM LOGO NO RELATORIO
            Map<String, Object> params = new HashMap<>();
            URL logo = getClass().getClassLoader().getResource("relatorio/leaf_banner_green.png");
            ImageIcon image = new ImageIcon(logo);
            params.put("logo", image.getImage());

            //CARREGAR O ARQUIVO DE RELATORIO (LAYOUT)
            InputStream relatorio = getClass().getClassLoader().getResourceAsStream("relatorio/pessoa_report.jasper");

            //CARREGAR OS REGISTROS (DADOS) QUE SERAO EXIBIDOS NO RELATORIO
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(facade.findAll());

            JasperPrint jasperPrint = null;
            try {
                //PREENCHE O RELATORIO PASSANDO POR PARAMETRO: ARQUIVO, LOGO, REGISTROS (DADOS)
                jasperPrint = JasperFillManager.fillReport(relatorio, params, dataSource);
            } catch (JRException e) {
                e.printStackTrace();
            }
            return jasperPrint;
        } catch (Exception ex) {
            ex.printStackTrace();
            return null;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bRelatorio.setText("Relatório");
        bRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(bRelatorio)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(bRelatorio)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRelatorioActionPerformed

        //O METODO generateReport COMBINA (JUNTA) O LAYOUT DO RELATORIO COM OS DADOS QUE SERAO EXIBIDOS
        JasperPrint jasper = generateReport();
//        Barcode barcode = new Barcode() {
//
//            @Override
//            public Rectangle getBarcodeSize() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//
//            @Override
//            public Rectangle placeBarcode(PdfContentByte pcb, Color color, Color color1) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//
//            @Override
//            public Image createAwtImage(Color color, Color color1) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//        };
//CRIA UMA JANELA AONDE O RELATORIO SERA EXIBIDO
        JasperViewer jv = new JasperViewer(jasper, false);
        //CRIA UM JDialog PARA O RELATORIO SER MODAL
        JDialog viewer = new JDialog(new javax.swing.JFrame(), "Visualização do Relatório", true);
        //DEFINE O TAMANHO DA JANELA
        viewer.setSize(800, 600);
        viewer.getContentPane().add(jv.getContentPane());
        //EXIBE O RELATORIO
        viewer.setVisible(true);

    }//GEN-LAST:event_bRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioForm dialog = new RelatorioForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRelatorio;
    // End of variables declaration//GEN-END:variables
}
