/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import entidade.Cliente;
import entidade.ItemVenda;
import entidade.Pagamento;
import entidade.Produto;
import entidade.Venda;
import facade.ClienteFacade;
import facade.PagamentoFacade;
import facade.ProdutoFacade;
import facade.VendaFacade;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author belarmino
 */
public class VendaVisao extends javax.swing.JDialog {

    /**
     * Creates new form VendaVisao
     */
    private Produto produtoItem;
    private Cliente clienteVenda;
    private Venda venda;
    private VendaFacade facade;
    private ItemVenda item;
    private ClienteFacade clienteFacade;
    private Pagamento pagamento;
    private PagamentoFacade pagFacade;
    double sub = 0;
    double acres = 0;
    double desc = 0;
    double total = 0;

    public VendaVisao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        enableComponents(false);
        facade = new VendaFacade();
        clienteFacade = new ClienteFacade();
        jtfCliente.setEnabled(false);
        jtfProduto.setEnabled(false);
        jftPreco.setEnabled(false);
        jftSubtotal.setEnabled(false);
        jftTotal.setEnabled(false);
    }

    private void enableComponents(boolean status) {
        jtfQuantidade.setEnabled(status);
        jftAcrescimo.setEnabled(status);
        jftDesconto.setEnabled(status);
        jtfParcelas.setEnabled(status);
        jbtAbrir.setEnabled(!status);
        jbtBuscarCliente.setEnabled(!jbtAbrir.isEnabled());
        jbtBuscarProduto.setEnabled(!jbtAbrir.isEnabled());
        jbtCalcular.setEnabled(!jbtAbrir.isEnabled());
        jbtAdicionar.setEnabled(!jbtAbrir.isEnabled());
        jcbFormaPagto.setEnabled(!jbtAbrir.isEnabled());
        jtItemVenda.setEnabled(!jbtAbrir.isEnabled());
        jbtCancelar.setEnabled(status);
        jbtComfirmar.setEnabled(!jbtAbrir.isEnabled());
        jlbAcrescimo.setEnabled(status);
        jlbCliente.setEnabled(status);
        jlbDesconto.setEnabled(status);
        jlbFormaPagto.setEnabled(status);
        jlbParcelas.setEnabled(status);
        jlbPreco.setEnabled(status);
        jlbProduto.setEnabled(status);
        jlbQuantidade.setEnabled(status);
        jlbSubtotal.setEnabled(status);
        jlbTotal.setEnabled(status);
        jbtRetirar.setEnabled(jbtAdicionar.isEnabled());

    }

    private void clearProduct() {
        jtfProduto.setText(null);
        jtfQuantidade.setText(null);
    }

    private void updateTable() {
        itemVendaList.clear();
        itemVendaList.addAll(facade.searchItemByStatus());
    }

    private void limpaCampos() {
        jtfCliente.setText(null);
        jtfProduto.setText(null);
        jtfQuantidade.setText(null);
        jftPreco.setText(null);
        jftAcrescimo.setText(null);
        jftDesconto.setText(null);
        jftSubtotal.setText(null);
        jtfParcelas.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        vendaEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("db_tcc_miqueiasPU").createEntityManager();
        produtoQuery = java.beans.Beans.isDesignTime() ? null : vendaEntityManager.createQuery("SELECT p FROM Produto p");
        produtoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(produtoQuery.getResultList());
        itemVendaQuery = java.beans.Beans.isDesignTime() ? null : vendaEntityManager.createQuery("SELECT i FROM ItemVenda i WHERE i.status != 'closed'");
        itemVendaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(itemVendaQuery.getResultList());
        jpCliente = new javax.swing.JPanel();
        jlbCliente = new javax.swing.JLabel();
        jbtBuscarCliente = new javax.swing.JButton();
        jtfCliente = new javax.swing.JTextField();
        jpProduto = new javax.swing.JPanel();
        jlbProduto = new javax.swing.JLabel();
        jbtBuscarProduto = new javax.swing.JButton();
        jlbQuantidade = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JTextField();
        jtfProduto = new javax.swing.JTextField();
        jbtAdicionar = new javax.swing.JButton();
        jlbPreco = new javax.swing.JLabel();
        jftPreco = new javax.swing.JFormattedTextField();
        jpCarrinho = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtItemVenda = new javax.swing.JTable();
        jbtRetirar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jbtAbrir = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtFechar = new javax.swing.JButton();
        jbtComfirmar = new javax.swing.JButton();
        jbtCalcular = new javax.swing.JButton();
        jpPagamento = new javax.swing.JPanel();
        jlbSubtotal = new javax.swing.JLabel();
        jlbDesconto = new javax.swing.JLabel();
        jftSubtotal = new javax.swing.JFormattedTextField();
        jftDesconto = new javax.swing.JFormattedTextField();
        jlbAcrescimo = new javax.swing.JLabel();
        jftAcrescimo = new javax.swing.JFormattedTextField();
        jlbTotal = new javax.swing.JLabel();
        jftTotal = new javax.swing.JFormattedTextField();
        jlbFormaPagto = new javax.swing.JLabel();
        jcbFormaPagto = new javax.swing.JComboBox();
        jlbParcelas = new javax.swing.JLabel();
        jtfParcelas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jpCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbCliente.setText("Cliente");

        jbtBuscarCliente.setText("Buscar");
        jbtBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarClienteActionPerformed(evt);
            }
        });

        jtfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpClienteLayout = new javax.swing.GroupLayout(jpCliente);
        jpCliente.setLayout(jpClienteLayout);
        jpClienteLayout.setHorizontalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpClienteLayout.setVerticalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCliente)
                    .addComponent(jbtBuscarCliente)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbProduto.setText("Produto:");

        jbtBuscarProduto.setText("Buscar");
        jbtBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarProdutoActionPerformed(evt);
            }
        });

        jlbQuantidade.setText("Quantidade:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtItemVenda, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.quantidade}"), jtfQuantidade, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtItemVenda, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.produto.descricao}"), jtfProduto, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jbtAdicionar.setText("Adicionar");
        jbtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAdicionarActionPerformed(evt);
            }
        });

        jlbPreco.setText("Preço Unitário:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtItemVenda, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.produto.precoUnitario}"), jftPreco, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jpProdutoLayout = new javax.swing.GroupLayout(jpProduto);
        jpProduto.setLayout(jpProdutoLayout);
        jpProdutoLayout.setHorizontalGroup(
            jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbProduto)
                    .addComponent(jlbPreco))
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jftPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtAdicionar))
                    .addGroup(jpProdutoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpProdutoLayout.setVerticalGroup(
            jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbProduto)
                    .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbQuantidade)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtAdicionar)
                    .addComponent(jlbPreco)
                    .addComponent(jftPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCarrinho.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtItemVenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtItemVenda.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, itemVendaList, jtItemVenda);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${produto}"));
        columnBinding.setColumnName("Produto");
        columnBinding.setColumnClass(entidade.Produto.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidade}"));
        columnBinding.setColumnName("Quantidade");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${subtotal}"));
        columnBinding.setColumnName("Subtotal");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jtItemVenda);
        if (jtItemVenda.getColumnModel().getColumnCount() > 0) {
            jtItemVenda.getColumnModel().getColumn(0).setResizable(false);
            jtItemVenda.getColumnModel().getColumn(1).setResizable(false);
            jtItemVenda.getColumnModel().getColumn(2).setResizable(false);
        }

        jbtRetirar.setText("Retirar");
        jbtRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCarrinhoLayout = new javax.swing.GroupLayout(jpCarrinho);
        jpCarrinho.setLayout(jpCarrinhoLayout);
        jpCarrinhoLayout.setHorizontalGroup(
            jpCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCarrinhoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtRetirar)))
                .addContainerGap())
        );
        jpCarrinhoLayout.setVerticalGroup(
            jpCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtRetirar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Add.png"))); // NOI18N
        jbtAbrir.setText("Abrir");
        jbtAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAbrirActionPerformed(evt);
            }
        });

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Cancel.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Home.png"))); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });

        jbtComfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Save.png"))); // NOI18N
        jbtComfirmar.setText("Comfirmar");
        jbtComfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtComfirmarActionPerformed(evt);
            }
        });

        jbtCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagem/Calculator.png"))); // NOI18N
        jbtCalcular.setText("Calcular");
        jbtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtComfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAbrir)
                    .addComponent(jbtFechar)
                    .addComponent(jbtComfirmar)
                    .addComponent(jbtCalcular)
                    .addComponent(jbtCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbSubtotal.setText("SubTotal:");

        jlbDesconto.setText("Desconto:");

        jftSubtotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jlbAcrescimo.setText("Acrescimo:");

        jftAcrescimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftAcrescimoActionPerformed(evt);
            }
        });

        jlbTotal.setText("Total:");

        jlbFormaPagto.setText("Forma de pagto:");

        jcbFormaPagto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro", "Cartão", "Cheque" }));

        jlbParcelas.setText("Parcelas:");

        javax.swing.GroupLayout jpPagamentoLayout = new javax.swing.GroupLayout(jpPagamento);
        jpPagamento.setLayout(jpPagamentoLayout);
        jpPagamentoLayout.setHorizontalGroup(
            jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSubtotal)
                    .addComponent(jlbTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jftSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jftTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPagamentoLayout.createSequentialGroup()
                        .addComponent(jlbDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbAcrescimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPagamentoLayout.createSequentialGroup()
                        .addComponent(jlbFormaPagto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbParcelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPagamentoLayout.setVerticalGroup(
            jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSubtotal)
                    .addComponent(jlbDesconto)
                    .addComponent(jftSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbAcrescimo)
                    .addComponent(jftAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTotal)
                    .addComponent(jftTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbFormaPagto)
                    .addComponent(jcbFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbParcelas)
                    .addComponent(jtfParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarProdutoActionPerformed
        String name = jtfProduto.getText();
        ProdutoBuscaVisao pbv = new ProdutoBuscaVisao(null, true, name);
        pbv.setVisible(true);
    }//GEN-LAST:event_jbtBuscarProdutoActionPerformed

    private void jbtBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarClienteActionPerformed
        String name = jtfCliente.getText();
        ClienteBuscaVisao cbv = new ClienteBuscaVisao(null, true, name);
        cbv.setVisible(true);
    }//GEN-LAST:event_jbtBuscarClienteActionPerformed

    private void jtfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClienteActionPerformed

    private void jftAcrescimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftAcrescimoActionPerformed
        // TODO add your handling code here:18319032
    }//GEN-LAST:event_jftAcrescimoActionPerformed

    private void validaProduto(ItemVenda item) {
        boolean val = true;
        ItemVenda iv;
        ItemVenda novo;
        for (int i = 0; i < itemVendaList.size(); i++) {
            iv = itemVendaList.get(i);
            if (iv.getProduto().getDescricao().equals(item.getProduto().getDescricao())) {
                novo = itemVendaList.get(i);
                itemVendaList.remove(i);
                //.setQuantidade(itemVendaList.get(i).getQuantidade() + item.getQuantidade());
                novo.setQuantidade(novo.getQuantidade() + item.getQuantidade());
                novo.setSubtotal(novo.getSubtotal() + item.getSubtotal());
                itemVendaList.add(i, novo);
                System.out.println("forforfor");
                val = false;
            }
        }
        if (val) {
            itemVendaList.add(item);
            System.out.println("ififififif");
        }

    }
    private void jbtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAdicionarActionPerformed
        if (jtfProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o produto!", null, JOptionPane.INFORMATION_MESSAGE);
        } else if (jtfQuantidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade do produto!", null, JOptionPane.INFORMATION_MESSAGE);

        } else {

            venda.setClient(clienteVenda);
            venda.setData(new Date());

            int qtd = Integer.parseInt(jtfQuantidade.getText());
            item = new ItemVenda();
            item.setProduto(produtoItem);
            item.setQuantidade(qtd);
            item.setSale(venda);
            item.setStatus("a receber");
            item.setSubtotal(produtoItem.getPrecoUnitario() * qtd);

            boolean op = validaEstoque(produtoItem, item);

            if (op) {
                validaProduto(item);
                for (ItemVenda i : itemVendaList) {
                    sub += i.getSubtotal();
                }
                jftSubtotal.setText("" + sub);

            } else {

                JOptionPane.showMessageDialog(null, "Estoque insuficiente!", null, JOptionPane.WARNING_MESSAGE);
                int op1 = JOptionPane.showConfirmDialog(null, "Deseja vender mesmo assim?");
                if (op1 == 0) {
                    validaProduto(item);
                    for (ItemVenda i : itemVendaList) {
                        sub += i.getSubtotal();
                    }
                    jftSubtotal.setText("" + sub);
                    jftPreco.setText(null);
                } else {

                    produtoItem = new Produto();
                    item = new ItemVenda();
                    jftPreco.setText(null);
                }
            }
            clearProduct();
        }
    }//GEN-LAST:event_jbtAdicionarActionPerformed
    private boolean validaEstoque(Produto produto, ItemVenda item) {
        boolean tem = true;
        ProdutoFacade fac = new ProdutoFacade();
        Produto p = fac.searchByCode(produto.getCodigo());
        if (item.getQuantidade() > produto.getQuantidade()) {
            tem = false;
        }
        return tem;
    }
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            setClient();
        } catch (Exception e) {
        }
        try {
            setProduct();
            jftPreco.setText("" + produtoItem.getPrecoUnitario());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jbtAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAbrirActionPerformed
        enableComponents(true);
        venda = new Venda();
    }//GEN-LAST:event_jbtAbrirActionPerformed

    private void jbtComfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtComfirmarActionPerformed
        if (venda != null) {
            try {
                venda.setTotal(total);
                venda.setStatus("a receber");
                venda.setFormaPagto(jcbFormaPagto.getSelectedItem().toString());
                venda.setParcelas(Integer.parseInt(jtfParcelas.getText()));

                try {
                    facade.create(venda);
                    for (ItemVenda iv : itemVendaList) {
                        iv.setStatus("closed");
                        iv.setSale(venda);
                        facade.createItem(iv);
                    }
                    JOptionPane.showMessageDialog(null, "Conclusão de Venda!");
                } catch (Exception e) {
                }

                int op = JOptionPane.showConfirmDialog(null, "Deseja abrir pagamento?");
                if (op == 0) {
                    pagamento = new Pagamento(venda, true);
                    PagamentoVisao pv = new PagamentoVisao(null, true);
                    this.dispose();
                    pv.setVisible(true);
                } else {
                    pagamento.setVenda(venda);
                    pagamento.setCliente(venda.getClient().getNome());
                    pagamento.setParcelas(venda.getParcelas());
                    pagamento.setStatus(venda.getStatus());
                    pagamento.setTotal(venda.getTotal());
                    pagamento.setValorParcela(venda.getTotal() / venda.getParcelas());
                    pagFacade.create(pagamento);
                    limpaCampos();
                    enableComponents(false);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na operação da Venda!", null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtComfirmarActionPerformed

    private void jbtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalcularActionPerformed
        calculaTotal();
    }//GEN-LAST:event_jbtCalcularActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        enableComponents(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtFecharActionPerformed

    private void jbtRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRetirarActionPerformed
        if (jtItemVenda.isRowSelected(jtItemVenda.getSelectedRow())) {
            itemVendaList.remove(jtItemVenda.getSelectedRow());
            // double subt = 
            //jftSubtotal.setText(""+sub);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
    }//GEN-LAST:event_jbtRetirarActionPerformed

    private void setClient() {
        clienteVenda = ClienteBuscaVisao.cliente;
        jtfCliente.setText(ClienteBuscaVisao.cliente.getNome());
    }

    private void setProduct() {
        produtoItem = ProdutoBuscaVisao.produto;
        jtfProduto.setText(ProdutoBuscaVisao.produto.getDescricao());
    }

    private void calculaTotal() {

        if (jftDesconto.getText().isEmpty() && !jftAcrescimo.getText().isEmpty()) {
            acres = Double.parseDouble(jftAcrescimo.getText());
            total = sub + acres;
            jftTotal.setText("" + total);
        } else if (!jftDesconto.getText().isEmpty() && jftAcrescimo.getText().isEmpty()) {
            desc = Double.parseDouble(jftDesconto.getText());
            total = sub - desc;
            jftTotal.setText("" + total);
        } else if (!jftDesconto.getText().isEmpty() && !jftAcrescimo.getText().isEmpty()) {
            desc = Double.parseDouble(jftDesconto.getText());
            acres = Double.parseDouble(jftAcrescimo.getText());
            total = (sub - desc) + acres;
            jftTotal.setText("" + total);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaVisao dialog = new VendaVisao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<entidade.ItemVenda> itemVendaList;
    private javax.persistence.Query itemVendaQuery;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtAbrir;
    private javax.swing.JButton jbtAdicionar;
    private javax.swing.JButton jbtBuscarCliente;
    private javax.swing.JButton jbtBuscarProduto;
    private javax.swing.JButton jbtCalcular;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtComfirmar;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JButton jbtRetirar;
    private javax.swing.JComboBox jcbFormaPagto;
    private javax.swing.JFormattedTextField jftAcrescimo;
    private javax.swing.JFormattedTextField jftDesconto;
    private javax.swing.JFormattedTextField jftPreco;
    private javax.swing.JFormattedTextField jftSubtotal;
    private javax.swing.JFormattedTextField jftTotal;
    private javax.swing.JLabel jlbAcrescimo;
    private javax.swing.JLabel jlbCliente;
    private javax.swing.JLabel jlbDesconto;
    private javax.swing.JLabel jlbFormaPagto;
    private javax.swing.JLabel jlbParcelas;
    private javax.swing.JLabel jlbPreco;
    private javax.swing.JLabel jlbProduto;
    private javax.swing.JLabel jlbQuantidade;
    private javax.swing.JLabel jlbSubtotal;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JPanel jpCarrinho;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpPagamento;
    private javax.swing.JPanel jpProduto;
    private javax.swing.JTable jtItemVenda;
    private javax.swing.JTextField jtfCliente;
    private javax.swing.JTextField jtfParcelas;
    private javax.swing.JTextField jtfProduto;
    private javax.swing.JTextField jtfQuantidade;
    private java.util.List<entidade.Produto> produtoList;
    private javax.persistence.Query produtoQuery;
    private javax.persistence.EntityManager vendaEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
